In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Load the dataset
df = pd.read_csv('imdb_movies_shows.csv')

In [3]:
df

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN
1,Taxi Driver,MOVIE,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0
2,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0
3,Life of Brian,MOVIE,1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0
4,The Exorcist,MOVIE,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0
...,...,...,...,...,...,...,...,...,...,...,...
5801,Fine Wine,MOVIE,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,tt13857480,6.9,39.0
5802,Edis Starlight,MOVIE,2021,NaN,74,"['music', 'documentation']",[],NaN,NaN,NaN,NaN
5803,Clash,MOVIE,2021,NaN,88,"['family', 'drama']","['NG', 'CA']",NaN,tt14620732,6.5,32.0
5804,Shadow Parties,MOVIE,2021,NaN,116,"['action', 'thriller']",[],NaN,tt10168094,6.2,9.0
5805,Mighty Little Bheem: Kite Festival,SHOW,2021,NaN,0,"['family', 'comedy', 'animation']",[],1.0,tt13711094,8.8,16.0

In [19]:
def summary(df):
    print(f'data shape: {df.shape}')
    summ = pd.DataFrame(df.dtypes, columns=['data type'])
    summ['#missing'] = df.isnull().sum().values 
    summ['%missing'] = df.isnull().sum().values / len(df) * 100
    summ['#unique'] = df.nunique().values
    desc = pd.DataFrame(df.describe(include='all').transpose())
    summ['min'] = desc['min'].values
    summ['max'] = desc['max'].values
    summ['average'] = desc['mean'].values
    summ['standard_deviation'] = desc['std'].values
    summ['first value'] = df.loc[0].values
    summ['second value'] = df.loc[1].values
    summ['third value'] = df.loc[2].values
    
    return summ

In [20]:
summary(df).style.background_gradient(cmap='YlOrBr')

data shape: (5362, 12)

KeyError: 0

In [4]:
# Task 1: Change genres and country features to be comma-separated values.
df['genres'] = df['genres'].apply(lambda x: ', '.join(eval(x)) if pd.notnull(x) else 'NO_GENRE')
df['production_countries'] = df['production_countries'].apply(lambda x: ', '.join(eval(x)) if pd.notnull(x) else 'NO_COUNTRY')

In [5]:
df

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,documentation,US,1.0,NaN,NaN,NaN
1,Taxi Driver,MOVIE,1976,R,113,"crime, drama",US,NaN,tt0075314,8.3,795222.0
2,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"comedy, fantasy",GB,NaN,tt0071853,8.2,530877.0
3,Life of Brian,MOVIE,1979,R,94,comedy,GB,NaN,tt0079470,8.0,392419.0
4,The Exorcist,MOVIE,1973,R,133,horror,US,NaN,tt0070047,8.1,391942.0
...,...,...,...,...,...,...,...,...,...,...,...
5801,Fine Wine,MOVIE,2021,NaN,100,"romance, drama",NG,NaN,tt13857480,6.9,39.0
5802,Edis Starlight,MOVIE,2021,NaN,74,"music, documentation",,NaN,NaN,NaN,NaN
5803,Clash,MOVIE,2021,NaN,88,"family, drama","NG, CA",NaN,tt14620732,6.5,32.0
5804,Shadow Parties,MOVIE,2021,NaN,116,"action, thriller",,NaN,tt10168094,6.2,9.0
5805,Mighty Little Bheem: Kite Festival,SHOW,2021,NaN,0,"family, comedy, animation",,1.0,tt13711094,8.8,16.0

In [6]:
# Task 2: Format countries values to be characters.
df['production_countries'] = df['production_countries'].apply(lambda x: ''.join([i for i in x if i.isalpha()]))

In [7]:
df

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,documentation,US,1.0,NaN,NaN,NaN
1,Taxi Driver,MOVIE,1976,R,113,"crime, drama",US,NaN,tt0075314,8.3,795222.0
2,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"comedy, fantasy",GB,NaN,tt0071853,8.2,530877.0
3,Life of Brian,MOVIE,1979,R,94,comedy,GB,NaN,tt0079470,8.0,392419.0
4,The Exorcist,MOVIE,1973,R,133,horror,US,NaN,tt0070047,8.1,391942.0
...,...,...,...,...,...,...,...,...,...,...,...
5801,Fine Wine,MOVIE,2021,NaN,100,"romance, drama",NG,NaN,tt13857480,6.9,39.0
5802,Edis Starlight,MOVIE,2021,NaN,74,"music, documentation",,NaN,NaN,NaN,NaN
5803,Clash,MOVIE,2021,NaN,88,"family, drama",NGCA,NaN,tt14620732,6.5,32.0
5804,Shadow Parties,MOVIE,2021,NaN,116,"action, thriller",,NaN,tt10168094,6.2,9.0
5805,Mighty Little Bheem: Kite Festival,SHOW,2021,NaN,0,"family, comedy, animation",,1.0,tt13711094,8.8,16.0

In [8]:

# Task 3: Change the [] values in genres and production_countries to "NO_GENRE" and "NO_COUNTRY".
df['genres'] = df['genres'].apply(lambda x: 'NO_GENRE' if x == '' else x)
df['production_countries'] = df['production_countries'].apply(lambda x: 'NO_COUNTRY' if x == '' else x)

In [9]:
df

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,documentation,US,1.0,NaN,NaN,NaN
1,Taxi Driver,MOVIE,1976,R,113,"crime, drama",US,NaN,tt0075314,8.3,795222.0
2,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"comedy, fantasy",GB,NaN,tt0071853,8.2,530877.0
3,Life of Brian,MOVIE,1979,R,94,comedy,GB,NaN,tt0079470,8.0,392419.0
4,The Exorcist,MOVIE,1973,R,133,horror,US,NaN,tt0070047,8.1,391942.0
...,...,...,...,...,...,...,...,...,...,...,...
5801,Fine Wine,MOVIE,2021,NaN,100,"romance, drama",NG,NaN,tt13857480,6.9,39.0
5802,Edis Starlight,MOVIE,2021,NaN,74,"music, documentation",NO_COUNTRY,NaN,NaN,NaN,NaN
5803,Clash,MOVIE,2021,NaN,88,"family, drama",NGCA,NaN,tt14620732,6.5,32.0
5804,Shadow Parties,MOVIE,2021,NaN,116,"action, thriller",NO_COUNTRY,NaN,tt10168094,6.2,9.0
5805,Mighty Little Bheem: Kite Festival,SHOW,2021,NaN,0,"family, comedy, animation",NO_COUNTRY,1.0,tt13711094,8.8,16.0

In [10]:
# Task 4: Check the movie without the title.
print("Movies without title:")
print(df[df['title'].isnull()])

Movies without title:
     title   type  release_year age_certification  runtime    genres  \
1805   NaN  MOVIE          2015               NaN       11  NO_GENRE

     production_countries  seasons    imdb_id  imdb_score  imdb_votes
1805           NO_COUNTRY      NaN  tt4661188         NaN         NaN

In [11]:
# Task 5: Drop movies without imdb_id.
df = df.dropna(subset=['imdb_id'])

In [14]:
# Task 6: Group movies by type.
adult_ratings = ['TV-MA', 'R', 'NC-17']
supervision_ratings = ['PG', 'TV-14', 'G', 'PG-13', 'TV-PG']

In [17]:
import pandas as pd

# Load the dataset
df = pd.read_csv('imdb_movies_shows.csv')

# Task 1: Change genres and country features to be comma-separated values.
df['genres'] = df['genres'].apply(lambda x: ', '.join(eval(x)) if pd.notnull(x) else 'NO_GENRE')
df['production_countries'] = df['production_countries'].apply(lambda x: ', '.join(eval(x)) if pd.notnull(x) else 'NO_COUNTRY')

# Task 2: Format countries values to be characters.
df['production_countries'] = df['production_countries'].apply(lambda x: ''.join([i for i in x if i.isalpha()]))

# Task 3: Change the [] values in genres and production_countries to "NO_GENRE" and "NO_COUNTRY".
df['genres'] = df['genres'].apply(lambda x: 'NO_GENRE' if x == '' else x)
df['production_countries'] = df['production_countries'].apply(lambda x: 'NO_COUNTRY' if x == '' else x)

# Task 4: Check the movie without the title.
print("Movies without title:")
print(df[df['title'].isnull()])

# Task 5: Drop movies without imdb_id.
df = df.dropna(subset=['imdb_id'])

# Task 6: Group movies by type.
adult_ratings = ['TV-MA', 'R', 'NC-17']
supervision_ratings = ['PG', 'TV-14', 'G', 'PG-13', 'TV-PG']

# Convert 'age_certification' to numeric
df['age_certification'] = pd.to_numeric(df['age_certification'], errors='coerce')

# Create 'rating_group' based on age certification
df['rating_group'] = pd.cut(df['age_certification'], bins=[-1, 17, 100], labels=['Requires Supervision', 'Adult'])

# Task 7: Map ratings for children.
children_ratings = ['TV-Y', 'TV-G', 'TV-Y7']
df['rating_group'] = df['age_certification'].map(lambda x: 'Good For Children' if x in children_ratings else x)

# Task 8: Fill NaN values with 'Not Rated'.
df['rating_group'] = df['rating_group'].fillna('Not Rated')

# Display the modified DataFrame
print(df)

Movies without title:
     title   type  release_year age_certification  runtime    genres  \
1805   NaN  MOVIE          2015               NaN       11  NO_GENRE

     production_countries  seasons    imdb_id  imdb_score  imdb_votes
1805           NO_COUNTRY      NaN  tt4661188         NaN         NaN
                                   title   type  release_year  \
1                            Taxi Driver  MOVIE          1976
2        Monty Python and the Holy Grail  MOVIE          1975
3                          Life of Brian  MOVIE          1979
4                           The Exorcist  MOVIE          1973
5           Monty Python's Flying Circus   SHOW          1969
...                                  ...    ...           ...
5800         Momshies! Your Soul is Mine  MOVIE          2021
5801                           Fine Wine  MOVIE          2021
5803                               Clash  MOVIE          2021
5804                      Shadow Parties  MOVIE          2021
5805  Mighty Little Bheem: Kite Festival   SHOW          2021

      age_certification  runtime                     genres  \
1                   NaN      113               crime, drama
2                   NaN       91            comedy, fantasy
3                   NaN       94                     comedy
4                   NaN      133                     horror
5                   NaN       30           comedy, european
...                 ...      ...                        ...
5800                NaN      108                     comedy
5801                NaN      100             romance, drama
5803                NaN       88              family, drama
5804                NaN      116           action, thriller
5805                NaN        0  family, comedy, animation

     production_countries  seasons     imdb_id  imdb_score  imdb_votes  \
1                      US      NaN   tt0075314         8.3    795222.0
2                      GB      NaN   tt0071853         8.2    530877.0
3                      GB      NaN   tt0079470         8.0    392419.0
4                      US      NaN   tt0070047         8.1    391942.0
5                      GB      4.0   tt0063929         8.8     72895.0
...                   ...      ...         ...         ...         ...
5800                   PH      NaN  tt14412240         5.8        26.0
5801                   NG      NaN  tt13857480         6.9        39.0
5803                 NGCA      NaN  tt14620732         6.5        32.0
5804           NO_COUNTRY      NaN  tt10168094         6.2         9.0
5805           NO_COUNTRY      1.0  tt13711094         8.8        16.0

     rating_group
1       Not Rated
2       Not Rated
3       Not Rated
4       Not Rated
5       Not Rated
...           ...
5800    Not Rated
5801    Not Rated
5803    Not Rated
5804    Not Rated
5805    Not Rated

[5362 rows x 12 columns]

In [18]:
# Task 7: Map ratings for children.
children_ratings = ['TV-Y', 'TV-G', 'TV-Y7']
df['rating_group'] = df['age_certification'].map(lambda x: 'Good For Children' if x in children_ratings else x)

# Task 8: Fill NaN values with 'Not Rated'.
df['rating_group'] = df['rating_group'].fillna('Not Rated')

# Display the modified DataFrame
print(df)

                                   title   type  release_year  \
1                            Taxi Driver  MOVIE          1976
2        Monty Python and the Holy Grail  MOVIE          1975
3                          Life of Brian  MOVIE          1979
4                           The Exorcist  MOVIE          1973
5           Monty Python's Flying Circus   SHOW          1969
...                                  ...    ...           ...
5800         Momshies! Your Soul is Mine  MOVIE          2021
5801                           Fine Wine  MOVIE          2021
5803                               Clash  MOVIE          2021
5804                      Shadow Parties  MOVIE          2021
5805  Mighty Little Bheem: Kite Festival   SHOW          2021

      age_certification  runtime                     genres  \
1                   NaN      113               crime, drama
2                   NaN       91            comedy, fantasy
3                   NaN       94                     comedy
4                   NaN      133                     horror
5                   NaN       30           comedy, european
...                 ...      ...                        ...
5800                NaN      108                     comedy
5801                NaN      100             romance, drama
5803                NaN       88              family, drama
5804                NaN      116           action, thriller
5805                NaN        0  family, comedy, animation

     production_countries  seasons     imdb_id  imdb_score  imdb_votes  \
1                      US      NaN   tt0075314         8.3    795222.0
2                      GB      NaN   tt0071853         8.2    530877.0
3                      GB      NaN   tt0079470         8.0    392419.0
4                      US      NaN   tt0070047         8.1    391942.0
5                      GB      4.0   tt0063929         8.8     72895.0
...                   ...      ...         ...         ...         ...
5800                   PH      NaN  tt14412240         5.8        26.0
5801                   NG      NaN  tt13857480         6.9        39.0
5803                 NGCA      NaN  tt14620732         6.5        32.0
5804           NO_COUNTRY      NaN  tt10168094         6.2         9.0
5805           NO_COUNTRY      1.0  tt13711094         8.8        16.0

     rating_group
1       Not Rated
2       Not Rated
3       Not Rated
4       Not Rated
5       Not Rated
...           ...
5800    Not Rated
5801    Not Rated
5803    Not Rated
5804    Not Rated
5805    Not Rated

[5362 rows x 12 columns]